#!/usr/bin/env bash
# This script audits DNS records for a domain's subdomains.

# shellcheck disable=SC2086
query_subdomain() {
    local domain="$1"
    local subdomain="$2"

    dig "${subdomain}.${domain}" +noall +answer | awk -v sub="$subdomain" '
        NR == 1 {
            printf "The subdomain %s is a %s record and points to %s\n", sub, $4, $5
        }
    '
}

main() {
    local domain="$1"
    local subdomain="$2"

    if [ -n "$subdomain" ]; then
        query_subdomain "$domain" "$subdomain"
    else
        query_subdomain "$domain" "www"
        query_subdomain "$domain" "lb-01"
        query_subdomain "$domain" "web-01"
        query_subdomain "$domain" "web-02"
    fi
}

main "$@"
