#!/usr/bin/env bash
# Ignore SC2086

domain=$1
subdomain=$2

get_info() {
    local subd=$1
    result=$(dig ${subd}.${domain} | awk '/ANSWER SECTION:/ {getline; print $1, $4, $5}')

    name=$(echo $result | awk '{print $1}')
    type=$(echo $result | awk '{print $2}')
    ip=$(echo $result | awk '{print $3}')

    echo "The subdomain ${subd} is a ${type} record and points to ${ip}"
}

if [ -z "$subdomain" ]; then
    for subd in www lb-01 web-01 web-02
    do
        get_info $subd
    done
else
    get_info $subdomain
fi
